Add : 프로젝트 초기세팅
kseul/PuzzleAI-VOIDOC-Front pull request #1
Opened 2022-06-21 09:35 UTC by kseul

# PuzzleAI-VOIDOC-Front

### :: 구현 목표 
- 초기셋팅

<br />

### :: 구현 사항 
#### 1. 프로젝트 초기파일 생성 및 폴더 구조 셋팅
<img width="211" alt="스크린샷 2022-06-21 오후 6 32 29" src="https://user-images.githubusercontent.com/93895746/174767654-8213cfa2-b1ec-4a57-bb29-dd2a0ba2783c.png">

- `npx react-native init PuzzleAi --template react-native-template-typescript`
- src 폴더 아래에 assets, components, screens, styles, types 폴더 생성 및 초기 파일 셋팅
- App.tsx 작성완료 및 라이브러리 적용
- npm run ios 구동 확인
- npm run android 구동 확인

#### 3. styles - theme.ts 
- 피그마 자료 참고하여 기본 테마스타일(flex, fontSizes, colors) 작성

#### 4. react-navigation 라이브러리 설치
- `screens`, `safe-area-context`, `stack`, `tab`

### :: 기타 질문 및 특이 사항
- StyleSheet 사용관련해서 궁금한 것이 있습니다. 스타일컴포넌트 대신 StyleSheet으로 작성하라고 말씀 주셨는데, 스타일컴포넌트에서 사용되는 ThemeProvider 패키지 같은 전역 스타일기능은 StyleSheet에서 어떻게 처리하면 좋을지 질문드립니다.

2022-06-21 12:51 UTC, jasonkang14 requested changes
1. `svg`와 `png`를 모두 포함하지 않아도 됩니다.
2. 첫 날 피그마 사용법에서 말씀드렸던 것 처럼, 진료과목을 표시할 때는 text를 제외하고 이미지만 사용할 수 있습니다. 이미지만 export하는 방법을 보여드렸었는데 해당 방법을 참고하시면 좋겠습니다. 
3. 추가로 말씀 드렸던 것 처럼 앱은 용량을 최대한 작게 유지해야 합니다. 따라서 진료과목 아이콘, 의사 얼굴 등의 이미지는 로컬에서 저장하지 않고 서버에서 불러오는 방식으로 변경해주세요. 
4. 로컬에 저장해서 사용하는 이미지(로고,  닫기버튼, 뒤로가기 버튼)등은 x1 사이즈 아이콘만 저장하는 것이 아니라 x2, x3사이즈의 아이콘도 가지고 있어야 합니다. 다양한 디바이스의 크기에 대응해야하는 모바일 특성상 필요한 부분입니다. 자세한 내용은 [Static Image Resources](https://reactnative.dev/docs/images#static-image-resources)를 참고해주세요

2022-06-21 12:51 UTC, jasonkang14 commented on App.tsx
> +import Splash from './src/screens/Splash/Splash';
절대경로를 사용하도록 수정해주세요

2022-06-21 12:51 UTC, jasonkang14 commented on android/build.gradle
> +        compileSdkVersion = 31
compile 버전을 31로 설정한 이유가 있으신가요?

2022-06-21 12:51 UTC, jasonkang14 commented on ios/PuzzleAi/AppDelegate.mm
> +#import "AppDelegate.h"
파일 확장자가 `.m`이 아니고 `.mm`인가요?

2022-06-21 12:51 UTC, jasonkang14 commented on src/screens/DotList/DitList.tsx
> +const DitList = () => {
`Dit`가 어떤걸 뜻하나요?

2022-06-21 12:51 UTC, jasonkang14 commented on src/screens/Entry/Entry.tsx
> +const Splash = () => {
파일 이름은 entry인데 컴포넌트 이름은 Splash인 이유가 있나요?

2022-06-21 12:51 UTC, jasonkang14 commented on src/screens/Main/RsrvtList.tsx
> +const RsrvtList = () => {
Rsrvt는 무슨 뜻인가요?

2022-06-21 12:51 UTC, jasonkang14 commented on src/screens/Splash/Splash.tsx
> +const Splash = () => {
`Entry.tsx`에도 `Splash`가 있는데 중복됩니다

2022-06-21 12:51 UTC, jasonkang14 commented on src/styles/theme.ts
> +  fontLarge: '22px',
[react native style](https://reactnative.dev/docs/style)에는 `px`라는 단위가 없습니다

2022-06-22 04:55 UTC, kseul commented on ios/PuzzleAi/AppDelegate.mm
> +#import "AppDelegate.h"
react-native 에서 앱성능 향상을 목적으로 기존 .m 에서 .mm으로  업데이트 되었다고 합니다. 
해당내용은 https://honeystorage.tistory.com/340 링크를 참조하였습니다!

2022-06-22 05:35 UTC, kseul commented on App.tsx
> +import Splash from './src/screens/Splash/Splash';
타입스크립트 공식문서의 Base URL과 Path mapping을 참고하여 상대경로를 절대경로로 수정하였습니다.

2022-06-22 05:53 UTC, kseul commented on android/build.gradle
> +        compileSdkVersion = 31
파일 생성 후 기본으로 31로 설정되어 있었는데, 찾아보니 compileSdkVersion은 지원할 수 있는 가장 높은 API버전을 의미하는 것으로 이해했습니다. 그렇다면 가장 최신버전 '33' 으로 다시 지정하는 것이 좋을까요?

참고한 문서 입니다. https://duzi077.tistory.com/141

2022-06-22 05:54 UTC, kseul commented on src/screens/DotList/DitList.tsx
> +const DitList = () => {
Doc의 오타입니다. 수정하였습니다!

2022-06-22 05:55 UTC, kseul commented on src/screens/Entry/Entry.tsx
> +const Splash = () => {
Entry파일 내에 컴포넌트명 오타입니다. Entry 파일과 Splash 파일 각각 이름에 맞는 컴포넌트로 수정하였습니다.

2022-06-22 05:56 UTC, kseul commented on src/screens/Main/RsrvtList.tsx
> +const RsrvtList = () => {
Reservation 단축어입니다. 혹시 풀어서 쓰는 편이 좋을까요 ?

2022-06-22 05:57 UTC, kseul commented on src/screens/Splash/Splash.tsx
> +const Splash = () => {
말씀드린 컴포넌트명 오타입니다ㅠㅠ. Entry 파일과 Splash 파일 각각 이름에 맞는 컴포넌트로 수정하였습니다.

2022-06-22 05:57 UTC, kseul commented on src/styles/theme.ts
> +  fontLarge: '22px',
px 단위 삭제후 반영하였습니다!

2022-06-22 07:17 UTC, jasonkang14 commented on android/build.gradle
> +        compileSdkVersion = 31
제가 지난주에 init했을때는 24였는데 그새 변경이 되었나봅니다. 이건 수정하지 않으셔도 됩니다.

2022-06-22 07:19 UTC, jasonkang14 commented on src/screens/Main/RsrvtList.tsx
> +const RsrvtList = () => {
네네 변수명을 굳이 줄일 필요는 없습니다. 물론 너무 길다면 협의하게 줄이긴 하는데, 여기는 그정도 길이는 아닌 것 같습니다.
추가로 reservation은 식당 예약에 사용되는 단어라서, 서버랑 통일하여 appointment로 변경해주세요

2022-06-22 07:20 UTC, jasonkang14 requested changes

2022-06-22 07:20 UTC, jasonkang14 commented on src/styles/theme.ts
> +  fontLarge: '22',
숫자라면 굳이 string으로 선언하지 않고 22를 사용해도 되지 않을까요? 
추후에 스타일 적용하실 때 타입스크립트에서 에러를 발생시킬겁니다

2022-06-22 07:49 UTC, kseul commented on src/styles/theme.ts
> +  fontLarge: '22',
네 타입 수정하였습니다!

2022-06-22 07:50 UTC, kseul commented on src/screens/Main/RsrvtList.tsx
> +const RsrvtList = () => {
Appointment로 수정하여 반영하였습니다.

2022-06-22 14:19 UTC, jasonkang14 approved these changes
LGTM

2022-06-22 14:19 UTC, merged