[박주영] 캘린더 UI 작업
kseul/PuzzleAI-VOIDOC-Front pull request #11
Opened 2022-07-04 08:48 UTC by parkjooyoung0608

### :: 최근 작업 주제
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

### :: 구현 목표 
1. 캘린더 UI 작업
![123456](https://user-images.githubusercontent.com/72453080/177114403-e88248ba-1bdf-4a93-9901-19fecd8f0ad0.gif)
2. 최초 진입 시 오늘 날짜 활성화 처리
3. 선택한 날짜 활성화  처리
![22222](https://user-images.githubusercontent.com/72453080/177114390-445359fb-a366-425f-8b2b-ee455f19c036.gif)

<br />

### :: 구현 사항
1. 최초 진입 시 현재 년도와 월이 캘린더 헤더에 표시
2. 최초 진입 시 현재 오늘 날짜가 점선으로 표시
3. 이전 버튼 클릭 시 전달로 이동
4. 다음 버튼 클릭 시 다음달로 이동
5. 날짜 선택 시 선택한 날짜 활성화 표시

### :: 기타 질문 및 특이 사항
기타 사항
슬비님과 SignIn 과정에서 필요한 토큰 저장 및 가져오기에 관한 useFetch 함수를 작성 한 뒤 기능브랜치에서 데이터 통신 기능을 추가할 예정입니다.

2022-07-04 10:03 UTC, jasonkang14 requested changes

2022-07-04 10:03 UTC, jasonkang14 commented on src/screens/AppointmentCalendar/index.tsx
> +    const weekArr: any[] = [];
1. type을 ReactNode 등으로 설정할 수 있습니다. 
2. `.forEach()`한 후에 `.push()`하지 않고 `.map()`으로 하시면 불필요한 연산을 줄일 수 있습니다. 
3. `disabledDate`는 서버 연동 후 수정하실 예정이라 일단 하드코딩 하신거라고 이해하면 될까요?

2022-07-04 10:03 UTC, jasonkang14 commented on src/screens/AppointmentCalendar/index.tsx
> +    const weekArr: any[] = [];
여기는 변수 없이 값만 리턴해도 되니 `useMemo()`가 더 적절할 것 같습니다.

2022-07-04 10:03 UTC, jasonkang14 commented on src/screens/AppointmentCalendar/index.tsx
> +  const prevLast = new Date(selectedYear, selectedMonth - 1, 0);
여기부터 return전까지 모든 코드가 effectHook으로 들어가야 합니다.

2022-07-04 10:03 UTC, jasonkang14 commented on src/screens/AppointmentCalendar/index.tsx
> +  const [dayNumber, setDayNumber] = useState();
hook을 사용하는  코드들은 컴포넌트 상단에 위치하는 편이 가독성에 좋습니다.

2022-07-04 10:03 UTC, jasonkang14 commented on src/screens/AppointmentCalendar/index.tsx
> +        <FlatList
`FlatList`사용 좋습니다 👍

2022-07-04 10:03 UTC, jasonkang14 commented on src/screens/AppointmentCalendar/index.tsx
> +  const year = now.get('y');
effect hook밖에서 변수를 선언하면, 이전버튼 다음버튼을 누를 때마다 `dayjs()`를 계속 호출하게 됩니다.

2022-07-04 10:03 UTC, jasonkang14 commented on src/screens/AppointmentCalendar/index.tsx
> +  const prevLastDay = prevLast.getDay();
전반적으로 변수명이 더 직관적이었으면 좋겠습니다. 
`prevLast`는 어떤 값의 이전의 마지막 값인지
`todayLastDay`, `todayLastDate`는 오늘의 마지막날, 오늘의 마지막 날짜가 어떤 용도인지 파악이 어렵습니다.

2022-07-04 10:03 UTC, jasonkang14 commented on src/screens/AppointmentCalendar/index.tsx
> +  const todayLastDay = new Date(selectedYear, selectedMonth, 0).getDay();
`dayjs` 라이브러리보다 `Date()`를 사용했을 때 이점이 있나요?

2022-07-04 10:03 UTC, jasonkang14 commented on src/screens/AppointmentCalendar/index.tsx
> +  const [dayNumber, setDayNumber] = useState();
`dayNumber` 초기값이 없는데 용도가 뭔가요?

2022-07-04 10:03 UTC, jasonkang14 commented on src/screens/AppointmentCalendar/index.tsx
> +  const todayLastDay = new Date(selectedYear, selectedMonth, 0).getDay();
dayjs 라이브러리의 장점은 오늘 날짜를 선언하면 상당히 많은 값들을 가져올 수 있다는 것에 있습니다. 
지금 작성하신 코드를 기준으로 볼 때 
```javascript
const now = dayjs();
now.daysInMonth();                // 이번달이 몇 일까지 있는지
now.startOf('month').day()    // 이번달 1일이 무슨 요일인지
now.endOf('month').day()     // 이번달 마지막 날이 무슨 요일인지
now.startOf('month').day()   // 지난달 마지막 날이 몇 일인지
```
이런식으로 확인 가능합니다.

2022-07-06 17:49 UTC, parkjooyoung0608 commented on src/screens/AppointmentCalendar/index.tsx
> +  const prevLast = new Date(selectedYear, selectedMonth - 1, 0);
해당 내용에 대한 질문이 있습니다!
첫 렌더링 시에만 달력의 데이터 값을 넣고, 내용이 바뀔 경우에만 렌더링 되도록 관리하도록 하기위해서 effect hook을 사용하라는 뜻으로 이해했습니다.

그러나 `prevLast` 변수부터 return 전까지 포함된 변수와 함수는 `<FlatList>` 에서 달력의 날짜를 `data`로 받기 위한 변수와 `renderItem`으로 JSX Element 를 return해주는 함수( `renderDate()` )입니다!
```jsx
<FlatList
    data={dates}
    numColumns={7}
    renderItem={renderDate}
    keyExtractor={(item, index) => index.toString()}
  />
```
effect hook 내부에 해당 값들을 넣을 경우 변수와 함수를 참조하지 못하는 문제가 발생합니다.
![image](https://user-images.githubusercontent.com/72453080/177607885-c48673d8-b333-49ce-bab0-5a8c6ebb2eb0.png)

해당 내용에는 어떤 방식으로 접근해서 해결하는 것이 좋을까요?

2022-07-06 17:49 UTC, parkjooyoung0608 commented on src/screens/AppointmentCalendar/index.tsx
> +  const year = now.get('y');
네! effect hook 내부로 변경하였습니다!

2022-07-06 17:50 UTC, parkjooyoung0608 commented on src/screens/AppointmentCalendar/index.tsx
> +  const prevLastDay = prevLast.getDay();
네! 변수명 직관적으로 수정 했습니다!

2022-07-06 17:50 UTC, parkjooyoung0608 commented on src/screens/AppointmentCalendar/index.tsx
> +        <FlatList
감사합니다!!

2022-07-06 17:51 UTC, parkjooyoung0608 commented on src/screens/AppointmentCalendar/index.tsx
> +  const todayLastDay = new Date(selectedYear, selectedMonth, 0).getDay();
dayjs 라이브러리의 이해도가 부족했던 것 같습니다. 오늘 날짜 선언 후 가져올 수 있는 값들은 보여주신 코드로 적용했습니다!

질문 사항이 있습니다!
지난달 마지막 날이 몇일인지를 가져오고 싶은데 구글링과 공식문서를 참고하였지만 찾지 못했습니다.
위에 작성해주신 코드에서는
```js
now.startOf('month').day() // 이번달 1일이 무슨 요일인지
now.startOf('month').day() // 지난달 마지막 날이 몇 일인지
```
이 두 코드의 차이가 없습니다. 때문에 dayjs에서 지난달 마지막 날의 값을 가져오는게 가능한지가 궁금합니다!

2022-07-06 17:52 UTC, parkjooyoung0608 commented on src/screens/AppointmentCalendar/index.tsx
> +    const weekArr: any[] = [];
3. 네 맞습니다. 휴일에 관한 요일의 폰트 색상을 확인해보기위해 하드코딩한 내용입니다! 지우고 기본 스타일로 맞춰서 다시 올렸습니다.

2022-07-06 17:53 UTC, parkjooyoung0608 commented on src/screens/AppointmentCalendar/index.tsx
> +    const weekArr: any[] = [];
상세한 피드백 감사합니다!! `.map()`변경 후 코드가 간결하게 바뀌었습니다!

변경하는 작업에서 
- `returnWeek()` 함수 자체가 불필요한 작업임을 깨달았습니다.
- week의 내용이 상수데이터라고 판단했습니다.

`returnWeek()`함수 삭제 후 상수데이터를 컴포넌트 return 문 안에서 바로 `.map()` 으로 작업했습니다.
간단한 작업이다보니 `useMemo()`의 사용이 불필요해 졌다고 판단해서 제외했습니다!

ReactNode type 에 관한 내용에서 궁금한 부분이 생겨서 질문남깁니다.
1. `returnWeek()` 함수가 JSX 문법을 return 했던 함수이기 때문에 ReactNode 등으로 타입 설정하라는 것으로 이해했습니다.
그렇다면 해당 함수를 return 문 안에 바로 작성 할 경우에도 타입을 지정해줘야할까요?

2. ReactNode에 관한 내용을 검색하다가 **컴포넌트를 담은 함수** 컴포넌트는 항상 JSX를 return하기 때문에 JSX.Element로 타입을 지정해야 한다는 내용을 봤습니다.
아래와 같이 컴포넌트 함수마다 타입을 지정해줘야 하는 건가요?
```jsx
const App (): JSX.Element {
	return (
    	...
    )
}
```
참고 링크 : [https://velog.io/@nemo/jsx.element](https://velog.io/@nemo/jsx.element)

2022-07-06 17:54 UTC, parkjooyoung0608 commented on src/screens/AppointmentCalendar/index.tsx
> +  const [dayNumber, setDayNumber] = useState();
hook 사용 코드들 상단으로 이동했습니다!

`dayNumber`은 이번달 날짜 중 선택된 날짜를 저장하는 State 입니다! 
변수명이 애매하고 초기값이 없었던 점에서 용도 파악이 안됐던 것 같습니다. 해당 내용은 
```js
const [dayNumber, setDayNumber] = useState();
```
에서
```js
  const [selectDayNumber, setSelectDayNumber] = useState(0);
```
로 변경했습니다!
가독성에 좀 더 신경쓰도록 하겠습니다🙇🏻‍♀️

2022-07-06 17:55 UTC, parkjooyoung0608 commented on src/screens/AppointmentCalendar/index.tsx
> +  const prevLast = new Date(selectedYear, selectedMonth - 1, 0);
해당 내용에 대한 질문이 있습니다!
첫 렌더링 시에만 달력의 데이터 값을 넣고, 내용이 바뀔 경우에만 렌더링 되도록 관리하도록 하기위해서 effect hook을 사용하라는 뜻으로 이해했습니다.

그러나 `prevLast` 변수부터 return 전까지 포함된 변수와 함수는 `<FlatList>` 에서 달력의 날짜를 `data`로 받기 위한 변수와 `renderItem`으로 JSX Element 를 return해주는 함수( `renderDate()` )입니다!
```jsx
<FlatList
    data={dates}
    numColumns={7}
    renderItem={renderDate}
    keyExtractor={(item, index) => index.toString()}
  />
```
effect hook 내부에 해당 값들을 넣을 경우 변수와 함수를 참조하지 못하는 문제가 발생합니다.
![image](https://user-images.githubusercontent.com/72453080/177607885-c48673d8-b333-49ce-bab0-5a8c6ebb2eb0.png)

해당 내용에는 어떤 방식으로 접근해서 해결하는 것이 좋을까요?

2022-07-07 01:50 UTC, jasonkang14 commented on src/screens/AppointmentCalendar/index.tsx
> +  const prevLast = new Date(selectedYear, selectedMonth - 1, 0);
`renderDate`는 함수인게 맞고, `dates`는 state로 관리하면 업데이트 될거에요

2022-07-07 01:51 UTC, jasonkang14 commented on src/screens/AppointmentCalendar/index.tsx
> +    const weekArr: any[] = [];
원래는 해주는게 맞는데, return값이 있으면 저런 부분은 자동적으로 넣어줘서 굳이 하지 않으셔도 됩니다.

2022-07-07 01:52 UTC, jasonkang14 commented on src/screens/AppointmentCalendar/index.tsx
> +  const todayLastDay = new Date(selectedYear, selectedMonth, 0).getDay();
제가 오타냈네요. 지난달 마지막날을 찾으려면 now에서 확인하는 것이 아니라 하루를 빼줘야합니다 .아마 이런식일거에요
```javascript
now.subtract('month', 1).endOf('month').day()
```

2022-07-07 02:04 UTC, jasonkang14 requested changes

2022-07-07 02:04 UTC, jasonkang14 commented on src/screens/AppointmentCalendar/index.tsx
> +  const year = now.get('y');
변경이 안 된 것 같은데요? `now`, `year`, `month`를 state나 ref로 할게 아니라면 컴포넌트 밖에서 선언해야합니다.

2022-07-07 02:04 UTC, jasonkang14 commented on src/screens/AppointmentCalendar/index.tsx
> +  const [selectedYear, setSelectedYear] = useState(year);
```jsx
<Text style={styles.calendarFontSize}>
    {selectedYear}년 {selectedMonth}월
</Text>
```

위 구문 때문에 연도와 월을 따로 관리하시는 것으로 보입니다. 
하지만 year, month정보는 dayjs 인스턴스에서 가져올 수 있습니다. 
(초기값에 넣으신 것처럼)
state가 많아지면 불필요한 렌더링이 발생할 가능성이 올라갑니다. 
`prevMonth()`부분을 보시면 1월일 경우 12월이 되면서 year, month state가 두 번 변경돼서 렌더링이 두 번 일어납니다. 
이 부분은 리액트 18에서 해결 되었는데, 지금 사용하는 리액트 버전이 17대라서 여기서는 렌더링이 두 번 일어납니다. 
렌더링 효율을 감안해서 관리하는 상태를 "선택된 날짜" 하나로 수정해주세요

2022-07-07 02:04 UTC, jasonkang14 commented on src/screens/AppointmentCalendar/index.tsx
> +  const prevMonthLast = new Date(selectedYear, selectedMonth - 1, 0);
1. 48번부터 71번은 effectHook안으로 옮겨져야하고, 
2. 답변 드린 것 처럼 dates를 state로 관리하면 Flatlist를 업데이트 할 수 있습니다.

2022-07-07 04:52 UTC, parkjooyoung0608 commented on src/screens/AppointmentCalendar/index.tsx
> +    const weekArr: any[] = [];
그렇군요! 답변 감사합니다!

2022-07-07 17:59 UTC, parkjooyoung0608 commented on src/screens/AppointmentCalendar/index.tsx
> +  const prevMonthLast = new Date(selectedYear, selectedMonth - 1, 0);
네! dates state로 관리하고 48-71은 effectHook 내부로 옮겼습니다!

2022-07-07 18:02 UTC, parkjooyoung0608 commented on src/screens/AppointmentCalendar/index.tsx
> +  const year = now.get('y');
이해가 부족했던 것 같습니다. 
now(`dayjs()`)는 컴포넌트 밖에 선언하고 `year`, `month`에 관한 내용은 state에 넣는 방식으로 수정했습니다!

2022-07-07 18:02 UTC, parkjooyoung0608 commented on src/screens/AppointmentCalendar/index.tsx
> +  const prevLast = new Date(selectedYear, selectedMonth - 1, 0);
네! 반영했습니다 감사합니다!

2022-07-07 18:03 UTC, parkjooyoung0608 commented on src/screens/AppointmentCalendar/index.tsx
> +  const year = now.get('y');
이해가 부족했던 것 같습니다.
now(dayjs())는 컴포넌트 밖에 선언하고 year, month에 관한 내용은 state에 넣는 방식으로 수정했습니다!

2022-07-07 18:04 UTC, parkjooyoung0608 commented on src/screens/AppointmentCalendar/index.tsx
> +  const [selectedYear, setSelectedYear] = useState(year);
네! 연도와 월을 따로 관리하지 않고 date를 다루는 하나의 state로 관리하도록 수정했습니다!

2022-07-08 00:58 UTC, jasonkang14 approved these changes
LGTM

2022-07-08 00:59 UTC, merged