useFetch / 통신 Context API 작성
kseul/PuzzleAI-VOIDOC-Front pull request #12
Opened 2022-07-06 05:07 UTC by parkjooyoung0608

### :: 최근 작업 주제
- [x] 기능 추가
- [ ] 리뷰 반영
- [x] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

### :: 구현 목표 
1. 통신 API 작성
2. useFetch 작성

### :: 구현 사항
1. 통신 API 작성
1-1. 사용자 인증 상태 조회를 위해 `Context API`를 사용해서 `AuthContext` 작성
1-2. `reducer`을 이용해서 로그인 상태 저장
1-3. `authContext`에 참조 함수 작성 후 `authContext`를 참조 해 SignIn 통신 작동 확인
1-3. App.tsx 파일에서 로그인 상태에 따라 페이지 이동하도록 구현

### :: 기타 질문 및 특이 사항

2022-07-06 07:19 UTC, jasonkang14 requested changes

2022-07-06 07:19 UTC, jasonkang14 commented on src/components/useFetch.tsx
> +  const [fetchData, setFetchDate] = useState([]);
1. 오타가 있습니다. `setFetchDate` -> `setFetchData`
2. fetch를 사용해서 받은 데이터가 array가 아닌 경우엔 어떻게 하나요?

2022-07-06 07:19 UTC, jasonkang14 commented on src/components/useFetch.tsx
> +      const getData = await fetch(url, {
토큰이 필요없는 경우의 request는 어떻게 핸들링하시나요?

2022-07-06 07:58 UTC, parkjooyoung0608 commented on src/components/useFetch.tsx
> +  const [fetchData, setFetchDate] = useState([]);
1. 오타 수정 완료했습니다!
2. 초기값을 array로 작성한 이유는 `res.result`를 fetchData로 상태저장 했을 경우 array가 나오기 때문에 작성해두고 초기값 변경하는 것을 놓쳤습니다. 
백엔드 통신 시 JSON 값으로 객체를 받아오는 것으로 알고 있습니다. 따라서 여러 컴포넌트에 useFetch함수를 동적으로 사용하기위해 fetch 상태 초기값을 `{}`로 변경했습니다.

2022-07-06 09:37 UTC, parkjooyoung0608 commented on src/components/useFetch.tsx
> +      const getData = await fetch(url, {
아까 말씀드린 것처럼 토큰이 필요한 경우만 따로 useFetch함수를 호출할 수 있도록 구현했습니다!

2022-07-07 01:49 UTC, jasonkang14 requested changes

2022-07-07 01:49 UTC, jasonkang14 commented on src/AuthContext.tsx
> +        loggedIn: false,
`loggedIn`은 이미 `false`라서 굳이 따로 선언하지 않으셔도 됩니다

2022-07-07 01:49 UTC, jasonkang14 commented on src/screens/SignUp/index.tsx
> +      userState.registered && navigation.navigate('SignIn');
&& 앞의 구문을 제거해주세요.  if문으로 이미 `userState.registered === true` 일때만 동작합니다

2022-07-07 02:20 UTC, parkjooyoung0608 commented on src/screens/SignUp/index.tsx
> +      userState.registered && navigation.navigate('SignIn');
네! 삭제했습니다.

2022-07-07 02:20 UTC, parkjooyoung0608 commented on src/AuthContext.tsx
> +        loggedIn: false,
네! 삭제했습니다~

2022-07-07 04:40 UTC, merged