[박주영] 로그인 페이지 로직 구현 / 통신 확인
kseul/PuzzleAI-VOIDOC-Front pull request #6
Opened 2022-06-29 05:15 UTC by parkjooyoung0608

# PuzzleAI-VOIDOC-Front

### :: 최근 작업 주제
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

### :: 구현 목표 
[ 로그인 페이지 기능 구현 ]
* 백엔드 로그인 통신
* 통신 성공 시 메인 페이지 네이게이터
![Jun-29-2022 14-01-12](https://user-images.githubusercontent.com/72453080/176355485-2d46dbfd-2fa7-4443-bf5b-fe915f285d24.gif)

<br />

### :: 구현 사항
1. eye icon toggle button 구현 : 비밀번호 표시/숨김 기능 구현

2. 사용자 편의를 위한 속성 추가
2-1. inputText 속성 추가
2-2. email input 에서 Tap 또는 Enter 시 비밀번호 input으로 넘어가고, 비밀번호 input 에서 Tap 또는 Enter 시 submit 되도록 구현

3. Submit 통신 로직 구현
3-1.  이메일이 입력되지 않았을 경우 경고창
3-2. 비밀번호가 입력되지 않았을 경우 경고창
3-3. 이메일이 정규식 표현에 맞지 않은 경우 경고창
3-4. 위의 조건이 모두 맞을 경우 통신
3-4-1. 통신 성공 시 메인페이지로 이동
3-4-2. 통신 실패 시 해당 사유에 대한 경고창

### :: 기타 질문 및 특이 사항

2022-06-29 06:49 UTC, jasonkang14 requested changes

2022-06-29 06:49 UTC, jasonkang14 commented on src/screens/SignIn/index.tsx
> +  const RegularExpression = /^[a-zA-Z0-9+-\_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$/;
1. 상수를 component내에 선언하면 안됩니다. 이러면 state가 변경될 때마다 이 값을 새로 선언하고 할당하게 됩니다. 
2. 변수명은 `camelCase`를 사용해주세요 
3. 해당 `Regex`가 사용되는 곳이 `onSubmit()`밖에 없으니 해당 함수 내부로  옮기는 것이  scope관리하기에 수월합니다.

2022-06-29 06:49 UTC, jasonkang14 commented on src/screens/SignIn/index.tsx
> +  const onChangeEmail = useCallback((text)=>{
`onChangeEmail`과 `onChangePassword`에 `useCallback`이 필요한 이유는 무엇인가요?

2022-06-29 07:30 UTC, parkjooyoung0608 commented on src/screens/SignIn/index.tsx
> +  const onChangeEmail = useCallback((text)=>{
함수를 리렌더링 될 때마다 재생산하지 않고 처음 렌더링시 한번만 사용하도록 하기 위해서 `useCallback` 을 사용했습니다!

2022-06-29 07:31 UTC, parkjooyoung0608 commented on src/screens/SignIn/index.tsx
> +  const RegularExpression = /^[a-zA-Z0-9+-\_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$/;
확인 후 변경했습니다.

2022-06-29 08:01 UTC, jasonkang14 requested changes

2022-06-29 08:01 UTC, jasonkang14 commented on src/screens/SignIn/index.tsx
> +    const regEx = /^[a-zA-Z0-9+-\_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$/;
위치를 33번줄로 옮겨주세요!
`email`, `password`에 문제가 있다면 regex는 필요 없으니까요

2022-06-29 08:01 UTC, jasonkang14 commented on src/screens/SignIn/index.tsx
> +import API from '~/src/config'
앞에 `~`가 붙는 경로와 붙지 않는 경로는 어떤 차이가 있나요?

2022-06-29 08:01 UTC, jasonkang14 commented on src/screens/SignIn/index.tsx
> +  const canGoMainPage = !email || !password
여기 있는 변수도 ref를 사용하던지, useMemo를 사용하는 식으로 수정되어야 합니다.

2022-06-29 08:01 UTC, jasonkang14 commented on src/screens/SignIn/index.tsx
> +  const onChangeEmail = useCallback((text)=>{
일단 저는 여기는 오히려 `useCallback`을 사용하는 것이 비효율적일 것 같은데요. 
그 이유는 [stackoverflow](https://stackoverflow.com/a/67043444)와 [블로그](https://kentcdodds.com/blog/usememo-and-usecallback)를 참고해주시고, 

네이티브에서는 프로파일링 세팅이 오래걸려서 같은 코드를 react 버전으로 테스트 했을 때
렌더링 시간은 여기서 `useCallback`을 사용하지 않는 방향이 0.2ms 유리합니다.
위가 `useCallback`을 사용하는 경우이고, 아래가 사용하지 않는 경우입니다.
<img width="195" alt="Screen Shot 2022-06-29 at 4 53 55 PM" src="https://user-images.githubusercontent.com/45306565/176383119-25664ba7-c4d7-4340-9ed3-c9c89f30c13e.png">

2022-06-29 08:01 UTC, jasonkang14 commented on src/screens/SignIn/index.tsx
> +  const canGoMainPage = !email || !password
regex와 같은 이유로요!

2022-06-29 08:03 UTC, jasonkang14 requested changes

2022-06-29 08:03 UTC, jasonkang14 commented on src/screens/SignIn/index.tsx
> +    const regEx = /^[a-zA-Z0-9+-\_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$/;
그리고 여기 useCallback도 필요 없을 것 같습니다. 
처음에는 여기는 사용해도 괜찮을 것 같았는데 로그인 화면에서 발생하는 state update는
아이디, 비밀번호 인풋 업데이트밖에 없으니 어차피 계속 해당 함수도 업데이트 될 것 같습니다

2022-06-29 08:03 UTC, jasonkang14 commented on src/screens/SignIn/index.tsx
> +          <Pressable
[디자인](https://www.figma.com/file/RntX0iiU6DOMmHQ5hyZs9U/%EA%B8%B0%EC%97%85%ED%98%91%EC%97%85%EA%B3%BC%EC%A0%9C?node-id=367%3A379)을 다시 보시면 로그인에는 비밀번호를 보이게 하는 버튼이 없습니다

2022-06-29 08:24 UTC, parkjooyoung0608 commented on src/screens/SignIn/index.tsx
> +  const canGoMainPage = !email || !password
통신 전에 로그인 하지 않아도 입력값만 있으면 이동하도록 구현하기 위해서 조건을 담는 용도로 사용했던 변수입니다! 통신 후에 사용하지 않는 변수여서 삭제했어야 했는데 놓쳤습니다ㅠㅠ 바로 삭제하도록 하겠습니다!

2022-06-29 08:37 UTC, parkjooyoung0608 commented on src/screens/SignIn/index.tsx
> +          <Pressable
피그마랑 기업협업 과제 ppt를 같이 보면서 작업하고 있습니다!

![스크린샷 2022-06-29 오후 5 36 15](https://user-images.githubusercontent.com/72453080/176391707-a9be0b04-128a-4f4a-9321-a676bd82235b.png)

해당 코멘트에 관한 질문사항이 있습니다! 
- 디자인은 피그마만 참고해서 작업하면 될까요? 
- 구현한 사항은 제거할까요?

2022-06-29 08:46 UTC, parkjooyoung0608 commented on src/screens/SignIn/index.tsx
> +    const regEx = /^[a-zA-Z0-9+-\_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$/;
네! 해당 사항 수정했습니다.

2022-06-29 09:40 UTC, parkjooyoung0608 commented on src/screens/SignIn/index.tsx
> +import API from '~/src/config'
해당 부분은 base url만 남기고 사용했을 경우 vscode상 에러는 뜨지 않지만 빌드 오류가 발생하는걸 볼 수 있습니다😭 
공통 사용 부분이기 때문에 내일 오전에 슬비님과 상의 후 새로운 브랜치에서 수정하도록 하겠습니다!

2022-06-29 09:46 UTC, parkjooyoung0608 commented on src/screens/SignIn/index.tsx
> +  const onChangeEmail = useCallback((text)=>{
자세하게 설명해주셔서 감사합니다🙇🏻‍♀️ `useCallback` 부분 삭제 후 반영했습니다!
해당 내용은 한번에 이해하긴 힘들어서 링크 주신 부분 참고해서 더 꼼꼼히 공부해보겠습니다!!

2022-06-30 03:48 UTC, jasonkang14 requested changes

2022-06-30 03:48 UTC, jasonkang14 commented on src/screens/SignIn/index.tsx
> +    }).then((response) => response.json()).then((data) =>
1. `response` 성공은 `status`로 먼저 구분하시고, 
2. `status`가 200대가 아닌 경우에는 `message`를 사용해주세요!
3. async ... await를 사용하도록 수정해주세요

2022-06-30 03:48 UTC, jasonkang14 commented on src/screens/SignIn/index.tsx
> +          <Pressable
넵 비밀번호 확인버튼은 제거해주시면 됩니다

2022-06-30 07:11 UTC, jasonkang14 approved these changes
LGTM

2022-06-30 07:11 UTC, merged